theme = "tearsheets-theme"
languageCode = "en-us"
baseurl = "http://localhost:8080/"
title = "Automated Benchmarking Report"

author = "Sean Kruzel"
copyright = "Copyright © 2021, Astrocyte Research, all rights reserved."

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
    name = "Portformer Fund Analysis"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "closedloop"
    github_repo = "https://github.com/AstrocyteResearch/tearsheets-theme"
    github_banner = true

    favicon = "favicon.ico"
